-- SQLite

CREATE TABLE IF NOT EXISTS Usuario (
    Id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Clave VARCHAR(200) NOT NULL
);


CREATE TABLE IF NOT EXISTS [Paciente] (
[Id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[UsuarioId] INTEGER  NULL,
[Cedula] VARCHAR(15)  NULL,
[Foto] VARCHAR(200)  NULL,
[Nombre] VARCHAR(50)  NULL,
[Apellido] VARCHAR(50)  NULL,
[TipoSangre] vaRCHAR(5)  NULL,
[Email] varCHAR(50)  NULL,
[Sexo] VARCHAR(1)  NULL,
[FechaNacimiento] DATE  NULL,
[AlergiasId] TEXT  NULL,
[SignoZodiacal] VARCHAR(20)  NULL,
CONSTRAINT fk_usuario FOREIGN KEY ( UsuarioId ) REFERENCES Usuario (Id)
);

CREATE TABLE if NOT EXISTS [Consulta] (
[Id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[PacienteId] INTEGER  NULL,
[UsuarioId] INTEGER  NULL,
[Fecha] DATE  NULL,
[Motivo] TEXT  NULL,
[Seguro] VARCHAR(100)  NULL,
[MontoPagado] FLOAT  NULL,
[Diagnostico] TEXT  NULL,
[Notas] TEXT  NULL,
[Archivo] VARCHAR(200)  NULL,
CONSTRAINT fk_usuario FOREIGN KEY ( UsuarioId ) REFERENCES Usuario (Id)
CONSTRAINT fk_paciente FOREIGN KEY ( PacienteId ) REFERENCES Paciente (Id)
);

CREATE TABLE if NOT EXISTS  [Alergia] (
[Id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[Nombre] VARCHAR(100)  NULL
);

